"""create prompt task asset review cost export tables

Revision ID: 4ecfe89d7af3
Revises: 51238682fed0
Create Date: 2026-05-21 02:02:13.673335
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '4ecfe89d7af3'
down_revision: str | None = '51238682fed0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_reasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Enum('character_inconsistent', 'face_pattern_wrong', 'color_wrong', 'scene_mismatch', 'style_drift', 'yingge_motion_wrong', 'motion_too_strong', 'motion_too_weak', 'bad_anatomy', 'duration_mismatch', 'model_error', 'prompt_weak', name='failure_reason_code'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('export_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'exported', name='export_plan_status'), server_default='draft', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_format', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_plans_project_id', 'export_plans', ['project_id'], unique=False)
    op.create_index('ix_export_plans_status', 'export_plans', ['status'], unique=False)
    op.create_table('prompt_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.Column('shot_id', sa.UUID(), nullable=True),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', 'negative', 'tts', 'storyboard', 'script', name='prompt_type'), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'optimized', 'locked', 'deprecated', name='prompt_status'), server_default='draft', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('positive_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('negative_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompt_drafts_panel_id', 'prompt_drafts', ['panel_id'], unique=False)
    op.create_index('ix_prompt_drafts_project_id', 'prompt_drafts', ['project_id'], unique=False)
    op.create_index('ix_prompt_drafts_shot_id', 'prompt_drafts', ['shot_id'], unique=False)
    op.create_index('ix_prompt_drafts_status', 'prompt_drafts', ['status'], unique=False)
    op.create_index('ix_prompt_drafts_type', 'prompt_drafts', ['type'], unique=False)
    op.create_table('generation_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('shot_id', sa.UUID(), nullable=True),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', 'tts', 'subtitle', 'prompt_optimize', name='generation_task_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'succeeded', 'failed', 'cancelled', name='generation_task_status'), server_default='pending', nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_drafts.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generation_tasks_model', 'generation_tasks', ['model'], unique=False)
    op.create_index('ix_generation_tasks_panel_id', 'generation_tasks', ['panel_id'], unique=False)
    op.create_index('ix_generation_tasks_project_id', 'generation_tasks', ['project_id'], unique=False)
    op.create_index('ix_generation_tasks_prompt_id', 'generation_tasks', ['prompt_id'], unique=False)
    op.create_index('ix_generation_tasks_provider', 'generation_tasks', ['provider'], unique=False)
    op.create_index('ix_generation_tasks_shot_id', 'generation_tasks', ['shot_id'], unique=False)
    op.create_index('ix_generation_tasks_status', 'generation_tasks', ['status'], unique=False)
    op.create_index('ix_generation_tasks_type', 'generation_tasks', ['type'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('shot_id', sa.UUID(), nullable=True),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', 'audio', 'subtitle', name='asset_type'), nullable=False),
    sa.Column('status', sa.Enum('candidate', 'accepted', 'rejected', 'archived', name='asset_status'), server_default='candidate', nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('thumbnail_uri', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('consistency_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('failure_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_drafts.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_panel_id', 'assets', ['panel_id'], unique=False)
    op.create_index('ix_assets_project_id', 'assets', ['project_id'], unique=False)
    op.create_index('ix_assets_shot_id', 'assets', ['shot_id'], unique=False)
    op.create_index('ix_assets_status', 'assets', ['status'], unique=False)
    op.create_index('ix_assets_task_id', 'assets', ['task_id'], unique=False)
    op.create_index('ix_assets_type', 'assets', ['type'], unique=False)
    op.create_table('asset_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('shot_id', sa.UUID(), nullable=True),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'needs_retry', name='review_status'), server_default='pending', nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('failure_reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reflection_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_reviews_asset_id', 'asset_reviews', ['asset_id'], unique=False)
    op.create_index('ix_asset_reviews_project_id', 'asset_reviews', ['project_id'], unique=False)
    op.create_index('ix_asset_reviews_shot_id', 'asset_reviews', ['shot_id'], unique=False)
    op.create_index('ix_asset_reviews_status', 'asset_reviews', ['status'], unique=False)
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('voice', sa.String(length=255), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('cost_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('estimated', 'actual', 'adjustment', name='cost_record_type'), server_default='actual', nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='CNY', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_records_asset_id', 'cost_records', ['asset_id'], unique=False)
    op.create_index('ix_cost_records_model', 'cost_records', ['model'], unique=False)
    op.create_index('ix_cost_records_project_id', 'cost_records', ['project_id'], unique=False)
    op.create_index('ix_cost_records_provider', 'cost_records', ['provider'], unique=False)
    op.create_index('ix_cost_records_task_id', 'cost_records', ['task_id'], unique=False)
    op.create_index('ix_cost_records_type', 'cost_records', ['type'], unique=False)
    op.create_table('image_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=50), nullable=True),
    sa.Column('prompt_strength', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('seed', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('reflection_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('shot_id', sa.UUID(), nullable=True),
    sa.Column('panel_id', sa.UUID(), nullable=True),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='reflection_severity'), server_default='info', nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_drafts.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['generation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reflection_notes_asset_id', 'reflection_notes', ['asset_id'], unique=False)
    op.create_index('ix_reflection_notes_project_id', 'reflection_notes', ['project_id'], unique=False)
    op.create_index('ix_reflection_notes_severity', 'reflection_notes', ['severity'], unique=False)
    op.create_index('ix_reflection_notes_shot_id', 'reflection_notes', ['shot_id'], unique=False)
    op.create_index('ix_reflection_notes_task_id', 'reflection_notes', ['task_id'], unique=False)
    op.create_table('subtitle_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timing_status', sa.String(length=100), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('video_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('motion_strength', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('mode', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_assets')
    op.drop_table('subtitle_assets')
    op.drop_index('ix_reflection_notes_task_id', table_name='reflection_notes')
    op.drop_index('ix_reflection_notes_shot_id', table_name='reflection_notes')
    op.drop_index('ix_reflection_notes_severity', table_name='reflection_notes')
    op.drop_index('ix_reflection_notes_project_id', table_name='reflection_notes')
    op.drop_index('ix_reflection_notes_asset_id', table_name='reflection_notes')
    op.drop_table('reflection_notes')
    op.drop_table('image_assets')
    op.drop_index('ix_cost_records_type', table_name='cost_records')
    op.drop_index('ix_cost_records_task_id', table_name='cost_records')
    op.drop_index('ix_cost_records_provider', table_name='cost_records')
    op.drop_index('ix_cost_records_project_id', table_name='cost_records')
    op.drop_index('ix_cost_records_model', table_name='cost_records')
    op.drop_index('ix_cost_records_asset_id', table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_table('audio_assets')
    op.drop_index('ix_asset_reviews_status', table_name='asset_reviews')
    op.drop_index('ix_asset_reviews_shot_id', table_name='asset_reviews')
    op.drop_index('ix_asset_reviews_project_id', table_name='asset_reviews')
    op.drop_index('ix_asset_reviews_asset_id', table_name='asset_reviews')
    op.drop_table('asset_reviews')
    op.drop_index('ix_assets_type', table_name='assets')
    op.drop_index('ix_assets_task_id', table_name='assets')
    op.drop_index('ix_assets_status', table_name='assets')
    op.drop_index('ix_assets_shot_id', table_name='assets')
    op.drop_index('ix_assets_project_id', table_name='assets')
    op.drop_index('ix_assets_panel_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_generation_tasks_type', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_status', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_shot_id', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_provider', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_prompt_id', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_project_id', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_panel_id', table_name='generation_tasks')
    op.drop_index('ix_generation_tasks_model', table_name='generation_tasks')
    op.drop_table('generation_tasks')
    op.drop_index('ix_prompt_drafts_type', table_name='prompt_drafts')
    op.drop_index('ix_prompt_drafts_status', table_name='prompt_drafts')
    op.drop_index('ix_prompt_drafts_shot_id', table_name='prompt_drafts')
    op.drop_index('ix_prompt_drafts_project_id', table_name='prompt_drafts')
    op.drop_index('ix_prompt_drafts_panel_id', table_name='prompt_drafts')
    op.drop_table('prompt_drafts')
    op.drop_index('ix_export_plans_status', table_name='export_plans')
    op.drop_index('ix_export_plans_project_id', table_name='export_plans')
    op.drop_table('export_plans')
    op.drop_table('failure_reasons')
    # ### end Alembic commands ###
