"""create project character script shot panel tables

Revision ID: 51238682fed0
Revises: 
Create Date: 2026-05-21 01:36:39.931311
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '51238682fed0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('star', sa.String(length=255), nullable=True),
    sa.Column('liangshan_role', sa.String(length=255), nullable=True),
    sa.Column('weapon', sa.String(length=255), nullable=True),
    sa.Column('yingge_role', sa.String(length=255), nullable=True),
    sa.Column('face_primary_color', sa.String(length=100), nullable=True),
    sa.Column('face_pattern', sa.String(length=255), nullable=True),
    sa.Column('color_symbolism', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_characters_name', 'characters', ['name'], unique=False)
    op.create_index('ix_characters_ranking', 'characters', ['ranking'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', 'completed', name='project_status'), server_default='draft', nullable=False),
    sa.Column('current_character_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('character_bibles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('identity_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inner_core_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cultural_visual_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative_material_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commercial_culture_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('positive_prompt_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forbidden_prompt_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consistency_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', name='uq_character_bibles_character_id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'generated', 'reviewed', 'locked', name='script_status'), server_default='draft', nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('ending', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scripts_character_id', 'scripts', ['character_id'], unique=False)
    op.create_index('ix_scripts_project_id', 'scripts', ['project_id'], unique=False)
    op.create_index('ix_scripts_status', 'scripts', ['status'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('shot_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('narration_segment', sa.Text(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=100), nullable=True),
    sa.Column('camera_movement', sa.String(length=255), nullable=True),
    sa.Column('scene', sa.String(length=255), nullable=True),
    sa.Column('consistency_status', sa.String(length=100), nullable=True),
    sa.Column('prompt_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'generating', 'completed', 'failed', name='shot_status'), server_default='draft', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_id', 'shot_no', name='uq_shots_script_id_shot_no')
    )
    op.create_index('ix_shots_character_id', 'shots', ['character_id'], unique=False)
    op.create_index('ix_shots_script_id', 'shots', ['script_id'], unique=False)
    op.create_index('ix_shots_status', 'shots', ['status'], unique=False)
    op.create_table('panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shot_id', sa.UUID(), nullable=False),
    sa.Column('panel_no', sa.Integer(), nullable=False),
    sa.Column('image_description', sa.Text(), nullable=True),
    sa.Column('camera', sa.String(length=255), nullable=True),
    sa.Column('motion', sa.String(length=255), nullable=True),
    sa.Column('prompt_status', sa.String(length=100), nullable=True),
    sa.Column('keyframe_status', sa.String(length=100), nullable=True),
    sa.Column('video_status', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'generating', 'completed', 'failed', name='panel_status'), server_default='draft', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'panel_no', name='uq_panels_shot_id_panel_no')
    )
    op.create_index('ix_panels_shot_id', 'panels', ['shot_id'], unique=False)
    op.create_index('ix_panels_status', 'panels', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_panels_status', table_name='panels')
    op.drop_index('ix_panels_shot_id', table_name='panels')
    op.drop_table('panels')
    op.drop_index('ix_shots_status', table_name='shots')
    op.drop_index('ix_shots_script_id', table_name='shots')
    op.drop_index('ix_shots_character_id', table_name='shots')
    op.drop_table('shots')
    op.drop_index('ix_scripts_status', table_name='scripts')
    op.drop_index('ix_scripts_project_id', table_name='scripts')
    op.drop_index('ix_scripts_character_id', table_name='scripts')
    op.drop_table('scripts')
    op.drop_table('character_bibles')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_characters_ranking', table_name='characters')
    op.drop_index('ix_characters_name', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
